version: '3.7'
services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    command: bin/dev
    entrypoint: docker/entrypoint.sh
    tty: true
    volumes:
      - ./:/app
    networks:
      - diplom
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    image: mysql
    env_file:
      - docker/database/.env
    volumes:
      - db_data:/var/lib/mysql/
    networks:
      - diplom
    ports:
      - 3306:3306

  nginx:
    image: nginx


volumes:
  db_data:

networks:
  diplom: