version: '3.7'
services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    volumes:
      - ./:/app
    networks:
      - diplom
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    image: postgres
    env_file:
      - docker/database/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - diplom
    ports:
      - 5432:5432

  nginx:
    image: nginx


volumes:
  db_data:

networks:
  diplom: